name: Deploy Preview

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy-preview:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test:run
      
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
        
    - name: Deploy Preview to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        destination_dir: preview/${{ github.event.number }}
        
    - name: Comment PR with preview URL
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo;
          const prNumber = context.issue.number;
          const previewUrl = `https://${owner}.github.io/${repo}/preview/${prNumber}/`;
          
          github.rest.issues.createComment({
            issue_number: prNumber,
            owner,
            repo,
            body: `🚀 Preview deployment ready! [View the preview here](${previewUrl})`
          });